homepage:
    pattern:  /{_locale}
    defaults: { _controller: DebbConfigBundle:Step:first, _locale: en }
    requirements:
        _locale: en|de

DebbConfigBundle:
    resource: "@DebbConfigBundle/Controller/"
    type:     annotation
